vendas_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: dpg-crged3aj1k6c739hbd40-a.oregon-postgres.render.com
      user: dbname_2xjq_user
      password: YtGtHb4GF2ud5KKtxXvfbaKGsTKWOlrR
      port: 5432
      dbname: dbname_2xjq
      schema: public
      threads: 4